#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed on the left bar and top bar)
name: "John McClane"

# Surname of your site (displayed on the left bar and top bar)
surname: mcclane

# Short bio or description (displayed on the left bar an top bar)
description: "Lieutenant officer at the NY Police ! yippee ki yay"
#description: "Look'up for the dragon but I found a princess"

# path of the profile picture image (displayed on the left bar)
image: "/assets/images/johnmcclane.jpg"

# Display the left bar
left_bar: true

# enable latex
latex: true

## OPTIONAL

# Your PGP key url if you have one (displayed on the left bar an top bar)
pgp :

# Your twitter github etc username if you have one
twitter: "mpgn_x64"
github: "mpgn"
stackoverflow: "2274530" # stackoverflow id
dribbble:
email:
facebook:
flickr:
instagram:
linkedin:
pinterest:
rss: # just type anything here for a working RSS icon
youtube: # channel/<your_long_string> or user/<user-name>
googleplus: # anything in your profile username that comes after plus.google.com/



# profil you recommand : (displayed on the left bar)
profiles:
  - username: "John Rambo"
    link: "https://github.com/mpgn/copper-jekyll-theme" 

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Or enable Google+ comment
google_plus: false

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "https://mpgn.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/copper-jekyll-theme"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:categories/:title/

# The release of Jekyll Now that you're using
version: v3.3.1

markdown: kramdown
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
